WITH super_mario_64 AS (
    INSERT INTO games(game_name, game_description, enabled)
    VALUES
    ('Super Mario 64', 'Super Mario 64 is a 1996 platform game for the Nintendo 64', TRUE)
    RETURNING id
),
inserted_levels AS (
    INSERT INTO game_levels(game_id, level_name, level_description)
    VALUES
    ((SELECT id FROM super_mario_64), 'Bob-omb Battlefield', 'Lobby'),
    ((SELECT id FROM super_mario_64), 'Whomp''s Fortress', 'Lobby'),
    ((SELECT id FROM super_mario_64), 'Jolly Roger Bay', 'Lobby'),
    ((SELECT id FROM super_mario_64), 'Cool, Cool Mountain', 'Lobby'),
    ((SELECT id FROM super_mario_64), 'Big Boo''s Haunt', 'Lobby'),
    ((SELECT id FROM super_mario_64), 'Hazy Maze Cave', 'Basement'),
    ((SELECT id FROM super_mario_64), 'Lethal Lava Land', 'Basement'),
    ((SELECT id FROM super_mario_64), 'Shifting Sand Land', 'Basement'),
    ((SELECT id FROM super_mario_64), 'Dire, Dire Docks', 'Basement'),
    ((SELECT id FROM super_mario_64), 'Snowman''s Land', 'Upstairs'),
    ((SELECT id FROM super_mario_64), 'Wet-Dry World', 'Upstairs'),
    ((SELECT id FROM super_mario_64), 'Tall, Tall Mountain', 'Upstairs'),
    ((SELECT id FROM super_mario_64), 'Tiny-Huge Island', 'Upstairs'),
    ((SELECT id FROM super_mario_64), 'Tick Tock Clock', 'Tippy'),
    ((SELECT id FROM super_mario_64), 'Rainbow Ride', 'Tippy'),
    ((SELECT id FROM super_mario_64), 'Bowser Stages', 'Various floors'),
    ((SELECT id FROM super_mario_64), 'Secret Stars', 'Various floors')
    RETURNING id, level_name
)

INSERT INTO game_objectives(level_id, objective_name)
VALUES
((SELECT id FROM inserted_levels WHERE level_name = 'Bob-omb Battlefield'), 'Big Bob-omb on the Summit'),
((SELECT id FROM inserted_levels WHERE level_name = 'Bob-omb Battlefield'), 'Footrace with Koopa the Quick'),
((SELECT id FROM inserted_levels WHERE level_name = 'Bob-omb Battlefield'), 'Shoot to the Island in the Sky'),
((SELECT id FROM inserted_levels WHERE level_name = 'Bob-omb Battlefield'), 'Find the 8 Red Coins'),
((SELECT id FROM inserted_levels WHERE level_name = 'Bob-omb Battlefield'), 'Mario Wings to the Sky'),
((SELECT id FROM inserted_levels WHERE level_name = 'Bob-omb Battlefield'), 'Behind Chain Chomp''s Gate'),
((SELECT id FROM inserted_levels WHERE level_name = 'Bob-omb Battlefield'), '100 Coins Star'),
((SELECT id FROM inserted_levels WHERE level_name = 'Bob-omb Battlefield'), '100 Coins + Reds'),
((SELECT id FROM inserted_levels WHERE level_name = 'Whomp''s Fortress'), 'Chip Off Whomp''s Block'),
((SELECT id FROM inserted_levels WHERE level_name = 'Whomp''s Fortress'), 'To the Top of the Fortress'),
((SELECT id FROM inserted_levels WHERE level_name = 'Whomp''s Fortress'), 'Shoot into the Wild Blue'),
((SELECT id FROM inserted_levels WHERE level_name = 'Whomp''s Fortress'), 'Red Coins on the Floating Isle'),
((SELECT id FROM inserted_levels WHERE level_name = 'Whomp''s Fortress'), 'Fall onto the Caged Island'),
((SELECT id FROM inserted_levels WHERE level_name = 'Whomp''s Fortress'), 'Blast Away the Wall'),
((SELECT id FROM inserted_levels WHERE level_name = 'Whomp''s Fortress'), '100 Coins Star'),
((SELECT id FROM inserted_levels WHERE level_name = 'Whomp''s Fortress'), '100 Coins + Reds'),
((SELECT id FROM inserted_levels WHERE level_name = 'Jolly Roger Bay'), 'Plunder in the Sunken Ship'),
((SELECT id FROM inserted_levels WHERE level_name = 'Jolly Roger Bay'), 'Can the Eel Come Out to Play?'),
((SELECT id FROM inserted_levels WHERE level_name = 'Jolly Roger Bay'), 'Treasure of the Ocean Cave'),
((SELECT id FROM inserted_levels WHERE level_name = 'Jolly Roger Bay'), 'Red Coins on the Ship Afloat'),
((SELECT id FROM inserted_levels WHERE level_name = 'Jolly Roger Bay'), 'Blast to the Stone Pillar'),
((SELECT id FROM inserted_levels WHERE level_name = 'Jolly Roger Bay'), 'Through the Jet Stream'),
((SELECT id FROM inserted_levels WHERE level_name = 'Jolly Roger Bay'), '100 Coins Star'),
((SELECT id FROM inserted_levels WHERE level_name = 'Jolly Roger Bay'), '100 Coins + Reds'),
((SELECT id FROM inserted_levels WHERE level_name = 'Cool, Cool Mountain'), 'Slip Slidin'' Away'),
((SELECT id FROM inserted_levels WHERE level_name = 'Cool, Cool Mountain'), 'Li''l Penguin Lost'),
((SELECT id FROM inserted_levels WHERE level_name = 'Cool, Cool Mountain'), 'Big Penguin Race'),
((SELECT id FROM inserted_levels WHERE level_name = 'Cool, Cool Mountain'), 'Frosty Slide for 8 Red Coins'),
((SELECT id FROM inserted_levels WHERE level_name = 'Cool, Cool Mountain'), 'Snowman''s Lost His Head'),
((SELECT id FROM inserted_levels WHERE level_name = 'Cool, Cool Mountain'), 'Wall Kicks Will Work'),
((SELECT id FROM inserted_levels WHERE level_name = 'Cool, Cool Mountain'), '100 Coins Star'),
((SELECT id FROM inserted_levels WHERE level_name = 'Cool, Cool Mountain'), '100 Coins + Reds'),
((SELECT id FROM inserted_levels WHERE level_name = 'Big Boo''s Haunt'), 'Go on a Ghost Hunt'),
((SELECT id FROM inserted_levels WHERE level_name = 'Big Boo''s Haunt'), 'Ride Big Boo''s Merry-Go-Round'),
((SELECT id FROM inserted_levels WHERE level_name = 'Big Boo''s Haunt'), 'Secret of the Haunted Books'),
((SELECT id FROM inserted_levels WHERE level_name = 'Big Boo''s Haunt'), 'Seek the 8 Red Coins'),
((SELECT id FROM inserted_levels WHERE level_name = 'Big Boo''s Haunt'), 'Big Boo''s Balcony'),
((SELECT id FROM inserted_levels WHERE level_name = 'Big Boo''s Haunt'), 'Eye to Eye in the Secret Room'),
((SELECT id FROM inserted_levels WHERE level_name = 'Big Boo''s Haunt'), '100 Coins Star'),
((SELECT id FROM inserted_levels WHERE level_name = 'Big Boo''s Haunt'), '100 Coins + Reds'),
((SELECT id FROM inserted_levels WHERE level_name = 'Hazy Maze Cave'), 'Swimming Beast in the Cavern'),
((SELECT id FROM inserted_levels WHERE level_name = 'Hazy Maze Cave'), 'Elevate for 8 Red Coins'),
((SELECT id FROM inserted_levels WHERE level_name = 'Hazy Maze Cave'), 'Metal-Head Mario Can Move!'),
((SELECT id FROM inserted_levels WHERE level_name = 'Hazy Maze Cave'), 'Navigating the Toxic Maze'),
((SELECT id FROM inserted_levels WHERE level_name = 'Hazy Maze Cave'), 'A-Maze-Ing Emergency Exit'),
((SELECT id FROM inserted_levels WHERE level_name = 'Hazy Maze Cave'), 'Watch for Rolling Rocks'),
((SELECT id FROM inserted_levels WHERE level_name = 'Hazy Maze Cave'), '100 Coins Star'),
((SELECT id FROM inserted_levels WHERE level_name = 'Hazy Maze Cave'), '100 Coins + Reds'),
((SELECT id FROM inserted_levels WHERE level_name = 'Lethal Lava Land'), 'Boil the Big Bully'),
((SELECT id FROM inserted_levels WHERE level_name = 'Lethal Lava Land'), 'Bully the Bullies'),
((SELECT id FROM inserted_levels WHERE level_name = 'Lethal Lava Land'), '8-Coin Puzzle with 15 Pieces'),
((SELECT id FROM inserted_levels WHERE level_name = 'Lethal Lava Land'), 'Red-Hot Log Rolling'),
((SELECT id FROM inserted_levels WHERE level_name = 'Lethal Lava Land'), 'Hot-Foot-It into the Volcano'),
((SELECT id FROM inserted_levels WHERE level_name = 'Lethal Lava Land'), 'Elevator Tour in the Volcano'),
((SELECT id FROM inserted_levels WHERE level_name = 'Lethal Lava Land'), '100 Coins Star'),
((SELECT id FROM inserted_levels WHERE level_name = 'Lethal Lava Land'), '100 Coins + Reds'),
((SELECT id FROM inserted_levels WHERE level_name = 'Shifting Sand Land'), 'In the Talons of the Big Bird'),
((SELECT id FROM inserted_levels WHERE level_name = 'Shifting Sand Land'), 'Shining Atop the Pyramid'),
((SELECT id FROM inserted_levels WHERE level_name = 'Shifting Sand Land'), 'Inside the Ancient Pyramid'),
((SELECT id FROM inserted_levels WHERE level_name = 'Shifting Sand Land'), 'Stand Tall on the Four Pillars'),
((SELECT id FROM inserted_levels WHERE level_name = 'Shifting Sand Land'), 'Free Flying for 8 Red Coins'),
((SELECT id FROM inserted_levels WHERE level_name = 'Shifting Sand Land'), 'Pyramid Puzzle'),
((SELECT id FROM inserted_levels WHERE level_name = 'Shifting Sand Land'), '100 Coins Star'),
((SELECT id FROM inserted_levels WHERE level_name = 'Shifting Sand Land'), '100 Coins + Reds'),
((SELECT id FROM inserted_levels WHERE level_name = 'Dire, Dire Docks'), 'Board Bowser''s Sub'),
((SELECT id FROM inserted_levels WHERE level_name = 'Dire, Dire Docks'), 'Chests in the Current'),
((SELECT id FROM inserted_levels WHERE level_name = 'Dire, Dire Docks'), 'Pole-Jumping for Red Coins'),
((SELECT id FROM inserted_levels WHERE level_name = 'Dire, Dire Docks'), 'Through the Jet Stream'),
((SELECT id FROM inserted_levels WHERE level_name = 'Dire, Dire Docks'), 'The Manta Ray''s Reward'),
((SELECT id FROM inserted_levels WHERE level_name = 'Dire, Dire Docks'), 'Collect the Caps...'),
((SELECT id FROM inserted_levels WHERE level_name = 'Dire, Dire Docks'), '100 Coins Star'),
((SELECT id FROM inserted_levels WHERE level_name = 'Dire, Dire Docks'), '100 Coins + Reds'),
((SELECT id FROM inserted_levels WHERE level_name = 'Snowman''s Land'), 'Snowman''s Big Head'),
((SELECT id FROM inserted_levels WHERE level_name = 'Snowman''s Land'), 'Chill with the Bully'),
((SELECT id FROM inserted_levels WHERE level_name = 'Snowman''s Land'), 'In the Deep Freeze'),
((SELECT id FROM inserted_levels WHERE level_name = 'Snowman''s Land'), 'Whirl from the Freezing Pond'),
((SELECT id FROM inserted_levels WHERE level_name = 'Snowman''s Land'), 'Shell Shreddin'' for Red Coins'),
((SELECT id FROM inserted_levels WHERE level_name = 'Snowman''s Land'), 'Into the Igloo'),
((SELECT id FROM inserted_levels WHERE level_name = 'Snowman''s Land'), '100 Coins Star'),
((SELECT id FROM inserted_levels WHERE level_name = 'Snowman''s Land'), '100 Coins + Reds'),
((SELECT id FROM inserted_levels WHERE level_name = 'Wet-Dry World'), 'Shocking Arrow Lifts!'),
((SELECT id FROM inserted_levels WHERE level_name = 'Wet-Dry World'), 'Top O'' the Town'),
((SELECT id FROM inserted_levels WHERE level_name = 'Wet-Dry World'), 'Secrets in the Shallows & Sky'),
((SELECT id FROM inserted_levels WHERE level_name = 'Wet-Dry World'), 'Express Elevator--Hurry Up!'),
((SELECT id FROM inserted_levels WHERE level_name = 'Wet-Dry World'), 'Go to Town for Red Coins'),
((SELECT id FROM inserted_levels WHERE level_name = 'Wet-Dry World'), 'Quick Race Through Downtown!'),
((SELECT id FROM inserted_levels WHERE level_name = 'Wet-Dry World'), '100 Coins Star'),
((SELECT id FROM inserted_levels WHERE level_name = 'Wet-Dry World'), '100 Coins + Reds'),
((SELECT id FROM inserted_levels WHERE level_name = 'Tall, Tall Mountain'), 'Scale the Mountain'),
((SELECT id FROM inserted_levels WHERE level_name = 'Tall, Tall Mountain'), 'Mystery of the Monkey Cage'),
((SELECT id FROM inserted_levels WHERE level_name = 'Tall, Tall Mountain'), 'Scary ''Shrooms, Red Coins'),
((SELECT id FROM inserted_levels WHERE level_name = 'Tall, Tall Mountain'), 'Mysterious Mountainside'),
((SELECT id FROM inserted_levels WHERE level_name = 'Tall, Tall Mountain'), 'Breathtaking View from Bridge'),
((SELECT id FROM inserted_levels WHERE level_name = 'Tall, Tall Mountain'), 'Blast to the Lonely Mushroom'),
((SELECT id FROM inserted_levels WHERE level_name = 'Tall, Tall Mountain'), '100 Coins Star'),
((SELECT id FROM inserted_levels WHERE level_name = 'Tall, Tall Mountain'), '100 Coins + Reds'),
((SELECT id FROM inserted_levels WHERE level_name = 'Tiny-Huge Island'), 'Pluck the Piranha Flower'),
((SELECT id FROM inserted_levels WHERE level_name = 'Tiny-Huge Island'), 'The Tip Top of the Huge Island'),
((SELECT id FROM inserted_levels WHERE level_name = 'Tiny-Huge Island'), 'Rematch with Koopa the Quick'),
((SELECT id FROM inserted_levels WHERE level_name = 'Tiny-Huge Island'), 'Five Itty Bitty Secrets'),
((SELECT id FROM inserted_levels WHERE level_name = 'Tiny-Huge Island'), 'Wiggler''s Red Coins'),
((SELECT id FROM inserted_levels WHERE level_name = 'Tiny-Huge Island'), 'Make Wiggler Squirm'),
((SELECT id FROM inserted_levels WHERE level_name = 'Tiny-Huge Island'), '100 Coins Star'),
((SELECT id FROM inserted_levels WHERE level_name = 'Tiny-Huge Island'), '100 Coins + Reds'),
((SELECT id FROM inserted_levels WHERE level_name = 'Tick Tock Clock'), 'Roll into the Cage'),
((SELECT id FROM inserted_levels WHERE level_name = 'Tick Tock Clock'), 'The Pit and the Pendulums'),
((SELECT id FROM inserted_levels WHERE level_name = 'Tick Tock Clock'), 'Get a Hand'),
((SELECT id FROM inserted_levels WHERE level_name = 'Tick Tock Clock'), 'Stomp on the Thwomp'),
((SELECT id FROM inserted_levels WHERE level_name = 'Tick Tock Clock'), 'Timed Jumps on Moving Bars'),
((SELECT id FROM inserted_levels WHERE level_name = 'Tick Tock Clock'), 'Stop Time for Red Coins'),
((SELECT id FROM inserted_levels WHERE level_name = 'Tick Tock Clock'), '100 Coins Star'),
((SELECT id FROM inserted_levels WHERE level_name = 'Tick Tock Clock'), '100 Coins + Reds'),
((SELECT id FROM inserted_levels WHERE level_name = 'Rainbow Ride'), 'Cruiser Crossing the Rainbow'),
((SELECT id FROM inserted_levels WHERE level_name = 'Rainbow Ride'), 'The Big House in the Sky'),
((SELECT id FROM inserted_levels WHERE level_name = 'Rainbow Ride'), 'Coins Amassed in a Maze'),
((SELECT id FROM inserted_levels WHERE level_name = 'Rainbow Ride'), 'Swingin'' in the Breeze'),
((SELECT id FROM inserted_levels WHERE level_name = 'Rainbow Ride'), 'Tricky Triangles!'),
((SELECT id FROM inserted_levels WHERE level_name = 'Rainbow Ride'), 'Somewhere Over the Rainbow'),
((SELECT id FROM inserted_levels WHERE level_name = 'Rainbow Ride'), '100 Coins Star'),
((SELECT id FROM inserted_levels WHERE level_name = 'Rainbow Ride'), '100 Coins + Reds'),
((SELECT id FROM inserted_levels WHERE level_name = 'Bowser Stages'), 'Bowser in the Dark World'),
((SELECT id FROM inserted_levels WHERE level_name = 'Bowser Stages'), 'Bowser in the Fire Sea'),
((SELECT id FROM inserted_levels WHERE level_name = 'Bowser Stages'), 'Bowser in the Sky'),
((SELECT id FROM inserted_levels WHERE level_name = 'Bowser Stages'), 'Bowser in the Dark World Reds'),
((SELECT id FROM inserted_levels WHERE level_name = 'Bowser Stages'), 'Bowser in the Fire Sea Reds'),
((SELECT id FROM inserted_levels WHERE level_name = 'Bowser Stages'), 'Bowser in the Sky Reds'),
((SELECT id FROM inserted_levels WHERE level_name = 'Secret Stars'), 'Tower of the Wing Cap'),
((SELECT id FROM inserted_levels WHERE level_name = 'Secret Stars'), 'Cavern of the Metal Cap'),
((SELECT id FROM inserted_levels WHERE level_name = 'Secret Stars'), 'Vanish Cap Under the Moat'),
((SELECT id FROM inserted_levels WHERE level_name = 'Secret Stars'), 'Wing Mario Over the Rainbow'),
((SELECT id FROM inserted_levels WHERE level_name = 'Secret Stars'), 'The Princess''s Secret Slide'),
((SELECT id FROM inserted_levels WHERE level_name = 'Secret Stars'), 'The Secret Aquarium'),
((SELECT id FROM inserted_levels WHERE level_name = 'Secret Stars'), 'Wing Mario Red Coins');